---
traces: 
  - path: "/home/smiano/dev/caida-equinix/equinix-nyc.dirA.20190117-125910.UTC.anon.64.100000.pcap"
    tx_queues: 4
numacore: 0
nbruns: 100000000
timeout: 60
max_mpps: -1
max_mbps: -1
write_csv: True
wait_enter: False
slow_mode: False
stats:
  - pci_id: 0000:3b:00.0
    file_name: "result_v1_core1.csv"
send_port_pci: 0000:3b:00.0
loglevel: INFO

